### ISSUE TITLE
Add a badge suggestion for people to use

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/linuxbrew.github.io#2]
This is what conda has:

Link to this page
Render an badge badge with the following Markdown:

```
[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat-square)](http://bioconda.github.io/recipes/abricate/README.html)
```

[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat-square)](http://bioconda.github.io/recipes/abricate/README.html)

**Comment by sjackman** [comment]
I like it! Nice idea.

```
[![brew install a2ps](https://img.shields.io/badge/brew%20install-a2ps-brightgreen.svg?style=flat-square)](http://brewformulas.org/a2ps)
```

[![brew install a2ps](https://img.shields.io/badge/brew%20install-a2ps-brightgreen.svg?style=flat-square)](http://brewformulas.org/a2ps)

Braumeister supports taps: http://braumeister.org/repos/Homebrew/homebrew-science/formula/bwa

I'm not sure that http://brewformulas.org supports taps.

**Comment by sjackman** [comment]
Repology indexes Brewsci/bio. https://repology.org/projects/?inrepo=homebrew_tap_brewsci_bio
Repology describes how to add badges here: https://repology.org/project/prokka/badges
