### ISSUE TITLE
Two installation instructions

### ISSUE THREAD

**Issue by denadai2** [Linuxbrew/linuxbrew.github.io#3]
Hello,
why are there two installation instructions on the home page? (different ones also!)
One is called "Install Linuxbrew (tl;dr)" the other "Installation". Thanks

**Comment by sjackman** [comment]
`tl;dr` is the summary and is short for "too long; didn't read".

**Comment by sjackman** [comment]
> (different ones also!)

They should be the same. Which part differs?
