### ISSUE TITLE
download link on main page downloads the website source (html/css), not linuxbrew itself

### ISSUE THREAD

**Issue by Osndok** [Linuxbrew/linuxbrew.github.io#4]
...and I'm sure that's not what is intended.

**Comment by sjackman** [comment]
Hehe. Yep. I hadn't noticed that. Thanks for the bug report. I'll have to see if I can modify the GitHub Jekyll template. To install Linuxbrew, follow these instructions:
http://linuxbrew.sh/#install-linuxbrew

**Comment by sjackman** [comment]
I've fixed this issue by removing the download link in commit https://github.com/Linuxbrew/linuxbrew.github.io/commit/b3b5bbf42371dcd80cadac4fd473d3b0ed4d879c
Thanks for your bug report, Robert!
