### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by euxaristia** [Linuxbrew/linuxbrew.github.io#5]
https://github.com/Linuxbrew/linuxbrew.github.io/blob/master/docs/Formula-Cookbook.md#homebrew-terminology

No longer goes anywhere, it's  a 404.

It's linked under the text "explained here" in index.md

```
Terminology (e.g. the difference between a Cellar, Tap, Cask and so forth) is explained here.
```

I'd like to fix it, if one could tell me a new link I'll replace it and do a PR

**Comment by sjackman** [comment]
Thanks, Jimmy. The new link is http://docs.brew.sh/Formula-Cookbook.html#homebrew-terminology
Please edit this original file: https://github.com/Linuxbrew/brew/blob/master/README.md
The `linuxbrew.github.io` repo is built from the `brew` repo.

**Comment by sjackman** [comment]
I've fixed the dead link with commit https://github.com/Linuxbrew/linuxbrew.github.io/commit/53e9c40a0a03b35a398548730f05b5c95f5c8260
Thanks for the bug report, Jimmy.

**Comment by euxaristia** [comment]
You're very welcome!
