### ISSUE TITLE
Update dependency installation for Fedora 

### ISSUE THREAD

**Issue by FranklinYu** [Linuxbrew/linuxbrew.github.io#7]
Latest Fedora uses `dnf` instead of `yum`, and [`rubygem-json`](https://apps.fedoraproject.org/packages/rubygem-json) is necessary. The line should be

```shell
sudo dnf group install 'Development Tools' && sudo dnf install curl file git python-setuptools rubygem-json
```

(Actually I suspect that `curl`, `file`, and `git` are installed by default, but that doesn't hurt anyway.)

**Comment by sjackman** [comment]
Thanks for the bug report, Franklin. If the `ruby` package is not installed at all, it should work just fine. Linuxbrew will install its own copy of Ruby. If however the `ruby` package is installed but `rubygem-json` is not installed, it may not work. I haven't tested that, but I've got a feeling it'll break. The two work arounds to fix it are…

1. `sudo dnf install rubygem-json` as you suggested
2. `brew vendor-install ruby`

A proper fix would need `setup-ruby-path` to detect whether Ruby has the `json` gem. A PR would be welcome to address this issue.
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/utils/ruby.sh#L40
 
I've opened PR https://github.com/Linuxbrew/brew/pull/506 to address the issue of yum vs dnf.
